services:
  client:
    container_name: lap2_project_test_client
     environment: 
      - PGUSER=importTeamName
      - PGHOST=db
      - PGPASSWORD=password
      - PGDATABASE=lifestyle_test
      - PGPORT=5432
      - NODE_ENV=test
    depends_on:
      - db
    tty: true 
  api:
    container_name: lap2_project_test_api
    build: ./client
    environment: 
      - PGUSER=importTeamName
      - PGHOST=db
      - PGPASSWORD=password
      - PGDATABASE=lifestyle_test
      - PGPORT=5432
      - NODE_ENV=test
    depends_on:
      - db
    tty: true
  db:
    container_name: lap2_project_test_db
    volumes:
      - "test_db:/var/lib/postgresql/data"
    environment: 
      - POSTGRES_DB=lifestyle_test
      - POSTGRES_PASSWORD=password
volumes:
  test_db:
networks: 
  default:
    name: lap2_project_test
