services:
  client:
    container_name: lap2Project_dev_client
    build: ./client
    image: lap2Project_client
    ports: 
      - 8080:8080
    working_dir: /code
    volumes:
      - type: bind
        source: ./client
        target: /code
    command: [ "http-server" ]
  api:
    container_name: lap2Project_dev_api
    ports: 
      - 3000:3000
    environment: 
      - PGUSER=importTeamName
      - PGHOST=db
      - PGPASSWORD=password
      - PGDATABASE=lifestyle
      - PGPORT=5432
      - NODE_ENV=development
    depends_on:
      - db
    command: bash -c "npm install && npm run seedDev && npm run dev"

  db:
    container_name: lap2Project_dev_db
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    environment: 
      - POSTGRES_DB=lifestyle
      - POSTGRES_USER=importTeamName
      - POSTGRES_PASSWORD=password
volumes:
  dbdata:
networks: 
  default:
    name: lap2Project_api
