services:
  api:
    container_name: lap2_project_dev_api
    ports: 
      - 3000:3000
    environment: 
      - PGUSER=importTeamName
      - PGHOST=db
      - PGPASSWORD=password
      - PGDATABASE=lifestyle
      - PGPORT=5432
      - NODE_ENV=development
    depends_on:
      - db
    command: bash -c "npm install && npm run seedDev && npm run dev"

  db:
    image: 'postgres:latest'
    container_name: lap2_project_dev_db
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    environment: 
      - POSTGRES_DB=lifestyle
      - POSTGRES_USER=importTeamName
      - POSTGRES_PASSWORD=password
volumes:
  dbdata:
networks: 
  default:
    name: lap2_project_api
